UMBREL_DATA_STORAGE_AUDIOBOOKS_DIR="${UMBREL_ROOT}/home/Audiobooks"
UMBREL_DATA_STORAGE_PODCASTS_DIR="${UMBREL_ROOT}/home/Audiobooks"
DESIRED_OWNER="1000:1000"

if [[ ! -d "${UMBREL_DATA_STORAGE_AUDIOBOOKS_DIR}" ]]; then
	mkdir -p "${UMBREL_DATA_STORAGE_AUDIOBOOKS_DIR}"

	chown "${DESIRED_OWNER}" "${UMBREL_DATA_STORAGE_AUDIOBOOKS_DIR}"
fi

if [[ ! -d "${UMBREL_DATA_STORAGE_PODCASTS_DIR}" ]]; then
	mkdir -p "${UMBREL_DATA_STORAGE_PODCASTS_DIR}"

	chown "${DESIRED_OWNER}" "${UMBREL_DATA_STORAGE_PODCASTS_DIR}"
fi
